<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BalanceOperationsMappingSeeder extends Seeder
{
    const TABLE_NAME = 'balance_operations';

    public function run(): void
    {

        $categories = DB::table('operation_categories')->pluck('id', 'code')->toArray();
        $data = [
            ['id' => 1, 'ref' => 'BAL01-CAT001-NUM001', 'operation_category_id' => $categories['CAT001'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 2, 'ref' => 'BAL02-CAT001-NUM001', 'operation_category_id' => $categories['CAT001'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 3, 'ref' => 'BAL03-CAT001-NUM001', 'operation_category_id' => $categories['CAT001'], 'operation' => 'WELCOME GIFT', 'direction' => 'IN', 'balance_type' => 'discount', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 4, 'ref' => 'BAL04-CAT001-NUM001', 'operation_category_id' => $categories['CAT001'], 'operation' => 'WELCOME GIFT', 'direction' => 'IN', 'balance_type' => 'tree', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 5, 'ref' => 'BAL05-CAT001-NUM001', 'operation_category_id' => $categories['CAT001'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'sms', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 6, 'ref' => 'BAL06-CAT001-NUM001', 'operation_category_id' => $categories['CAT001'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 7, 'ref' => 'BAL07-CAT001-NUM001', 'operation_category_id' => $categories['CAT001'], 'operation' => 'WELCOME GIFT', 'direction' => 'IN', 'balance_type' => 'chance', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 8, 'ref' => 'BAL01-CAT002-NUM001', 'operation_category_id' => $categories['CAT002'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 9, 'ref' => 'BAL02-CAT002-NUM001', 'operation_category_id' => $categories['CAT002'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 10, 'ref' => 'BAL03-CAT002-NUM001', 'operation_category_id' => $categories['CAT002'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'discount', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 11, 'ref' => 'BAL04-CAT002-NUM001', 'operation_category_id' => $categories['CAT002'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'tree', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 12, 'ref' => 'BAL05-CAT002-NUM001', 'operation_category_id' => $categories['CAT002'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'sms', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 13, 'ref' => 'BAL06-CAT002-NUM001', 'operation_category_id' => $categories['CAT002'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 14, 'ref' => 'BAL07-CAT002-NUM001', 'operation_category_id' => $categories['CAT002'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'chance', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 15, 'ref' => 'BAL01-CAT003-NUM001', 'operation_category_id' => $categories['CAT003'], 'operation' => 'SHARES SELL', 'direction' => 'OUT', 'balance_type' => 'cash', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'shareBalance', 'relatable_type' => 'default'],
            ['id' => 16, 'ref' => 'BAL01-CAT003-NUM002', 'operation_category_id' => $categories['CAT003'], 'operation' => 'ORDER SELL', 'direction' => 'OUT', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'item, sms, coupon'],
            ['id' => 17, 'ref' => 'BAL02-CAT003-NUM001', 'operation_category_id' => $categories['CAT003'], 'operation' => 'ORDER SELL', 'direction' => 'OUT', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'item, sms, coupon'],
            ['id' => 18, 'ref' => 'BAL03-CAT003-NUM001', 'operation_category_id' => $categories['CAT003'], 'operation' => 'ORDER SELL', 'direction' => 'OUT', 'balance_type' => 'discount', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'item, sms, coupon'],
            ['id' => 19, 'ref' => 'BAL05-CAT003-NUM001', 'operation_category_id' => $categories['CAT003'], 'operation' => 'SMS SELL', 'direction' => 'IN', 'balance_type' => 'sms', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'sms'],
            ['id' => 20, 'ref' => 'BAL06-CAT003-NUM001', 'operation_category_id' => $categories['CAT003'], 'operation' => 'SHARES SELL', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'cashBalance', 'relatable_type' => 'shares sell'],
            ['id' => 21, 'ref' => 'BAL01-CAT005-NUM001', 'operation_category_id' => $categories['CAT005'], 'operation' => 'CASH TO CASH', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 22, 'ref' => 'BAL01-CAT005-NUM002', 'operation_category_id' => $categories['CAT005'], 'operation' => 'CASH TO CASH', 'direction' => 'OUT', 'balance_type' => 'cash', 'parent_id' => 21, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 23, 'ref' => 'BAL01-CAT005-NUM003', 'operation_category_id' => $categories['CAT005'], 'operation' => 'CASH TO BFS_100', 'direction' => 'OUT', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 24, 'ref' => 'BAL02-CAT005-NUM001', 'operation_category_id' => $categories['CAT005'], 'operation' => 'CASH TO BFS_100', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => 23, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 25, 'ref' => 'BAL02-CAT005-NUM002', 'operation_category_id' => $categories['CAT005'], 'operation' => 'BFS_100 TO BFS_100', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 26, 'ref' => 'BAL02-CAT005-NUM003', 'operation_category_id' => $categories['CAT005'], 'operation' => 'BFS_100 TO BFS_100', 'direction' => 'OUT', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 27, 'ref' => 'BAL02-CAT006-NUM001', 'operation_category_id' => $categories['CAT006'], 'operation' => 'SHARES SELL', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'shareBalance', 'relatable_type' => 'default'],
            ['id' => 28, 'ref' => 'BAL03-CAT006-NUM001', 'operation_category_id' => $categories['CAT006'], 'operation' => 'FROM BFS_100', 'direction' => 'IN', 'balance_type' => 'discount', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'bfssBalance', 'relatable_type' => 'default'],
            ['id' => 29, 'ref' => 'BAL04-CAT007-NUM001', 'operation_category_id' => $categories['CAT007'], 'operation' => 'ORDER SELL', 'direction' => 'IN', 'balance_type' => 'tree', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'level'],
            ['id' => 30, 'ref' => 'BAL06-CAT006-NUM001', 'operation_category_id' => $categories['CAT006'], 'operation' => 'PRICE CHANGE BENEFITS ON PURCHASED SHARES', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'shareBalance', 'relatable_type' => 'default'],
            ['id' => 31, 'ref' => 'BAL06-CAT006-NUM002', 'operation_category_id' => $categories['CAT006'], 'operation' => 'COMPLIMENTARY BENEFITS ON PURCHASED SHARES', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'shareBalance', 'relatable_type' => 'default'],
            ['id' => 32, 'ref' => 'BAL06-CAT006-NUM003', 'operation_category_id' => $categories['CAT006'], 'operation' => 'VIP BENEFITS ON PURCHASED SHARES', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'shareBalance', 'relatable_type' => 'default'],
            ['id' => 33, 'ref' => 'BAL01-CAT006-NUM001', 'operation_category_id' => $categories['CAT006'], 'operation' => 'TREE REMUNERATION', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'treeBalance', 'relatable_type' => 'default'],
            ['id' => 34, 'ref' => 'BAL01-CAT006-NUM002', 'operation_category_id' => $categories['CAT006'], 'operation' => 'SOLDED SHARES', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'shareBalance', 'relatable_type' => 'default'],
            ['id' => 35, 'ref' => 'BAL01-CAT006-NUM003', 'operation_category_id' => $categories['CAT006'], 'operation' => 'JACKPOT WON', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'chancesBalance', 'relatable_type' => 'default'],
            ['id' => 36, 'ref' => 'BAL02-CAT006-NUM002', 'operation_category_id' => $categories['CAT006'], 'operation' => 'TREE REMUNERATION', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'treeBalance', 'relatable_type' => 'default'],
            ['id' => 37, 'ref' => 'BAL02-CAT006-NUM004', 'operation_category_id' => $categories['CAT006'], 'operation' => 'JACKPOT WON', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'chancesBalance', 'relatable_type' => 'default'],
            ['id' => 38, 'ref' => 'BAL01-CAT008-NUM001', 'operation_category_id' => $categories['CAT008'], 'operation' => 'DEALRUSH COMMISSION', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'deal'],
            ['id' => 39, 'ref' => 'BAL02-CAT008-NUM001', 'operation_category_id' => $categories['CAT008'], 'operation' => 'DEALRUSH COMMISSION', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'deal'],
            ['id' => 40, 'ref' => 'BAL01-CAT009-NUM001', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 41, 'ref' => 'BAL02-CAT009-NUM001', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 42, 'ref' => 'BAL03-CAT009-NUM001', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'discount', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 43, 'ref' => 'BAL04-CAT009-NUM001', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'tree', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 44, 'ref' => 'BAL05-CAT009-NUM001', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'sms', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 45, 'ref' => 'BAL06-CAT009-NUM001', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 46, 'ref' => 'BAL07-CAT009-NUM001', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT', 'direction' => 'IN', 'balance_type' => 'chance', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 47, 'ref' => 'BAL01-CAT010-NUM001', 'operation_category_id' => $categories['CAT010'], 'operation' => 'DETAILS ARCHIVATED', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'cashBalance', 'relatable_type' => 'history'],
            ['id' => 48, 'ref' => 'BAL02-CAT010-NUM001', 'operation_category_id' => $categories['CAT010'], 'operation' => 'DETAILS ARCHIVATED', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'bfssBalance', 'relatable_type' => 'history'],
            ['id' => 49, 'ref' => 'BAL03-CAT010-NUM001', 'operation_category_id' => $categories['CAT010'], 'operation' => 'DETAILS ARCHIVATED', 'direction' => 'IN', 'balance_type' => 'discount', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'discountBalance', 'relatable_type' => 'history'],
            ['id' => 50, 'ref' => 'BAL04-CAT010-NUM001', 'operation_category_id' => $categories['CAT010'], 'operation' => 'DETAILS ARCHIVATED', 'direction' => 'IN', 'balance_type' => 'tree', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'treeBalance', 'relatable_type' => 'history'],
            ['id' => 51, 'ref' => 'BAL05-CAT010-NUM001', 'operation_category_id' => $categories['CAT010'], 'operation' => 'DETAILS ARCHIVATED', 'direction' => 'IN', 'balance_type' => 'sms', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'smsBalance', 'relatable_type' => 'history'],
            ['id' => 52, 'ref' => 'BAL06-CAT010-NUM001', 'operation_category_id' => $categories['CAT010'], 'operation' => 'DETAILS ARCHIVATED', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'shareBalance', 'relatable_type' => 'history'],
            ['id' => 53, 'ref' => 'BAL07-CAT010-NUM001', 'operation_category_id' => $categories['CAT010'], 'operation' => 'DETAILS ARCHIVATED', 'direction' => 'IN', 'balance_type' => 'chance', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'chancesBalance', 'relatable_type' => 'history'],
            ['id' => 54, 'ref' => 'BAL04-CAT011-NUM001', 'operation_category_id' => $categories['CAT011'], 'operation' => 'TREE REMUNERATED', 'direction' => 'OUT', 'balance_type' => 'tree', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 55, 'ref' => 'BAL06-CAT011-NUM001', 'operation_category_id' => $categories['CAT011'], 'operation' => 'SOLDED SHARES', 'direction' => 'OUT', 'balance_type' => 'share', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 56, 'ref' => 'BAL07-CAT011-NUM001', 'operation_category_id' => $categories['CAT011'], 'operation' => 'JACKPOT WON', 'direction' => 'OUT', 'balance_type' => 'chance', 'parent_id' => null, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 57, 'ref' => 'BAL05-CAT011-NUM001', 'operation_category_id' => $categories['CAT011'], 'operation' => 'SMS CONSUMED', 'direction' => 'OUT', 'balance_type' => 'sms', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'sms content'],
            ['id' => 58, 'ref' => 'BAL06-CAT007-NUM001', 'operation_category_id' => $categories['CAT007'], 'operation' => 'SHARES SELL', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 59, 'ref' => 'BAL01-CAT007-NUM002', 'operation_category_id' => $categories['CAT007'], 'operation' => 'SHARES SELL', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 60, 'ref' => 'BAL02-CAT007-NUM003', 'operation_category_id' => $categories['CAT007'], 'operation' => 'SHARES SELL', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => 20, 'relatable' => true, 'relatable_model' => 'user', 'relatable_type' => 'default'],
            ['id' => 61, 'ref' => 'BAL01-CAT012-NUM001', 'operation_category_id' => $categories['CAT012'], 'operation' => 'TOP-UP WITH CARD', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => 20, 'relatable' => false, 'relatable_model' => null, 'relatable_type' => null],
            ['id' => 62, 'ref' => 'BAL01-CAT012-NUM002', 'operation_category_id' => $categories['CAT012'], 'operation' => 'CASH TOP-UP WITH VOUCHER', 'direction' => 'IN', 'balance_type' => 'cash', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'coupon'],
            ['id' => 63, 'ref' => 'BAL06-CAT006-NUM004', 'operation_category_id' => $categories['CAT006'], 'operation' => 'FROM BFS_100', 'direction' => 'IN', 'balance_type' => 'share', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'bfssBalance', 'relatable_type' => 'default'],
            ['id' => 64, 'ref' => 'BAL03-CAT009-NUM002', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT VOUCHER', 'direction' => 'IN', 'balance_type' => 'discount', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'discountBalance', 'relatable_type' => 'note'],
            ['id' => 65, 'ref' => 'BAL02-CAT009-NUM003', 'operation_category_id' => $categories['CAT009'], 'operation' => 'GIFT VOUCHER', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'bfssBalance', 'relatable_type' => 'note'],
            ['id' => 66, 'ref' => 'BAL02-CAT012-NUM004', 'operation_category_id' => $categories['CAT012'], 'operation' => 'BFS_100 TOP-UP WITH VOUCHER', 'direction' => 'IN', 'balance_type' => 'bfs', 'parent_id' => null, 'relatable' => true, 'relatable_model' => 'order', 'relatable_type' => 'coupon'],
        ];
        foreach ($data as $index => $item) {
            DB::table(self::TABLE_NAME)->updateOrInsert(
                ['id' => $item['id']],$item
            );

        }
    }
}
