<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BalanceOperationsMappingSeeder extends Seeder
{
    const TABLE_NAME = 'balance_operations';

    public function run(): void
    {

        DB::table('balance_operations')->insert([
            ['id' => 1, 'ref' => 'BAL01-CAT001-NUM001', 'operation_category_id' => 1, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'ref' => 'BAL02-CAT001-NUM001', 'operation_category_id' => 1, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'ref' => 'BAL03-CAT001-NUM001', 'operation_category_id' => 1, 'operation' => 'WELCOME GIFTGIFT', 'direction' => 'IN', 'balance_id' => 3, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'ref' => 'BAL04-CAT001-NUM001', 'operation_category_id' => 1, 'operation' => 'WELCOME GIFTGIFT', 'direction' => 'IN', 'balance_id' => 4, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'ref' => 'BAL05-CAT001-NUM001', 'operation_category_id' => 1, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 5, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'ref' => 'BAL06-CAT001-NUM001', 'operation_category_id' => 1, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'ref' => 'BAL07-CAT001-NUM001', 'operation_category_id' => 1, 'operation' => 'WELCOME GIFTGIFT', 'direction' => 'IN', 'balance_id' => 7, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'ref' => 'BAL01-CAT002-NUM001', 'operation_category_id' => 2, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'ref' => 'BAL02-CAT002-NUM001', 'operation_category_id' => 2, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'ref' => 'BAL03-CAT002-NUM001', 'operation_category_id' => 2, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 3, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'ref' => 'BAL04-CAT002-NUM001', 'operation_category_id' => 2, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 4, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'ref' => 'BAL05-CAT002-NUM001', 'operation_category_id' => 2, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 5, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'ref' => 'BAL06-CAT002-NUM001', 'operation_category_id' => 2, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'ref' => 'BAL07-CAT002-NUM001', 'operation_category_id' => 2, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 7, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'ref' => 'BAL01-CAT003-NUM001', 'operation_category_id' => 3, 'operation' => 'SHARES SELLGIFT', 'direction' => 'OUT', 'balance_id' => 1, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'shareBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'ref' => 'BAL01-CAT003-NUM002', 'operation_category_id' => 3, 'operation' => 'ORDER SELLGIFT', 'direction' => 'OUT', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'item, sms, coupon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'ref' => 'BAL02-CAT003-NUM001', 'operation_category_id' => 3, 'operation' => 'ORDER SELLGIFT', 'direction' => 'OUT', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'item, sms, coupon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'ref' => 'BAL03-CAT003-NUM001', 'operation_category_id' => 3, 'operation' => 'ORDER SELLGIFT', 'direction' => 'OUT', 'balance_id' => 3, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'item, sms, coupon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'ref' => 'BAL05-CAT003-NUM001', 'operation_category_id' => 3, 'operation' => 'SMS SELLGIFT', 'direction' => 'IN', 'balance_id' => 5, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'sms', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'ref' => 'BAL06-CAT003-NUM001', 'operation_category_id' => 3, 'operation' => 'SHARES SELLGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'cashBalance', 'relateble_types' => 'shares sell', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'ref' => 'BAL01-CAT005-NUM001', 'operation_category_id' => 4, 'operation' => 'CASH TO CASHGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 22, 'ref' => 'BAL01-CAT005-NUM002', 'operation_category_id' => 4, 'operation' => 'CASH TO CASHGIFT', 'direction' => 'OUT', 'balance_id' => 1, 'parent_operation_id' => '21', 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 23, 'ref' => 'BAL01-CAT005-NUM003', 'operation_category_id' => 4, 'operation' => 'CASH TO BFS_100GIFT', 'direction' => 'OUT', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 24, 'ref' => 'BAL02-CAT005-NUM001', 'operation_category_id' => 4, 'operation' => 'CASH TO BFS_100GIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => '23', 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 25, 'ref' => 'BAL02-CAT005-NUM002', 'operation_category_id' => 4, 'operation' => 'BFS_100 TO BFS_100GIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 26, 'ref' => 'BAL02-CAT005-NUM003', 'operation_category_id' => 4, 'operation' => 'BFS_100 TO BFS_100GIFT', 'direction' => 'OUT', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 27, 'ref' => 'BAL02-CAT006-NUM001', 'operation_category_id' => 5, 'operation' => 'SHARES SELLGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'shareBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 28, 'ref' => 'BAL03-CAT006-NUM001', 'operation_category_id' => 5, 'operation' => 'FROM BFS_100 GIFT', 'direction' => 'IN', 'balance_id' => 3, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'bfssBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 29, 'ref' => 'BAL04-CAT007-NUM001', 'operation_category_id' => 6, 'operation' => 'ORDER SELLGIFT', 'direction' => 'IN', 'balance_id' => 4, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'level', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 30, 'ref' => 'BAL06-CAT006-NUM001', 'operation_category_id' => 5, 'operation' => 'PRICE CHANGE BENEFITS ON PURCHASED SHARESGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'shareBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 31, 'ref' => 'BAL06-CAT006-NUM002', 'operation_category_id' => 5, 'operation' => 'COMPLIMENTARY BENEFITS ON PURCHASED SHARESGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'shareBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 32, 'ref' => 'BAL06-CAT006-NUM003', 'operation_category_id' => 5, 'operation' => 'VIP BENEFITS ON PURCHASED SHARESGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'shareBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 33, 'ref' => 'BAL01-CAT006-NUM001', 'operation_category_id' => 5, 'operation' => 'TREE REMUNARATIONGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'treeBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 34, 'ref' => 'BAL01-CAT006-NUM002', 'operation_category_id' => 5, 'operation' => 'SOLDED SHARESGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'shareBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 35, 'ref' => 'BAL01-CAT006-NUM003', 'operation_category_id' => 5, 'operation' => 'JACKPOT WONGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'chancesBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 36, 'ref' => 'BAL02-CAT006-NUM002', 'operation_category_id' => 5, 'operation' => 'TREE REMUNARATIONGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'treeBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 37, 'ref' => 'BAL02-CAT006-NUM004', 'operation_category_id' => 5, 'operation' => 'JACKPOT WONGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'chancesBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 38, 'ref' => 'BAL01-CAT008-NUM001', 'operation_category_id' => 7, 'operation' => 'DEALRUSH COMMISSIONGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'deal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 39, 'ref' => 'BAL02-CAT008-NUM001', 'operation_category_id' => 7, 'operation' => 'DEALRUSH COMMISSIONGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'deal', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 40, 'ref' => 'BAL01-CAT009-NUM001', 'operation_category_id' => 8, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 41, 'ref' => 'BAL02-CAT009-NUM001', 'operation_category_id' => 8, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 42, 'ref' => 'BAL03-CAT009-NUM001', 'operation_category_id' => 8, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 3, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 43, 'ref' => 'BAL04-CAT009-NUM001', 'operation_category_id' => 8, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 4, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 44, 'ref' => 'BAL05-CAT009-NUM001', 'operation_category_id' => 8, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 5, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 45, 'ref' => 'BAL06-CAT009-NUM001', 'operation_category_id' => 8, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 46, 'ref' => 'BAL07-CAT009-NUM001', 'operation_category_id' => 8, 'operation' => 'GIFTGIFT', 'direction' => 'IN', 'balance_id' => 7, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 47, 'ref' => 'BAL01-CAT010-NUM001', 'operation_category_id' => 9, 'operation' => 'DETAILS ARCHIVATEDGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'cashBalance', 'relateble_types' => 'history', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 48, 'ref' => 'BAL02-CAT010-NUM001', 'operation_category_id' => 9, 'operation' => 'DETAILS ARCHIVATEDGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'bfssBalance', 'relateble_types' => 'history', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 49, 'ref' => 'BAL03-CAT010-NUM001', 'operation_category_id' => 9, 'operation' => 'DETAILS ARCHIVATEDGIFT', 'direction' => 'IN', 'balance_id' => 3, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'discountBalance', 'relateble_types' => 'history', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 50, 'ref' => 'BAL04-CAT010-NUM001', 'operation_category_id' => 9, 'operation' => 'DETAILS ARCHIVATEDGIFT', 'direction' => 'IN', 'balance_id' => 4, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'treeBalance', 'relateble_types' => 'history', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 51, 'ref' => 'BAL05-CAT010-NUM001', 'operation_category_id' => 9, 'operation' => 'DETAILS ARCHIVATEDGIFT', 'direction' => 'IN', 'balance_id' => 5, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'smsBalance', 'relateble_types' => 'history', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 52, 'ref' => 'BAL06-CAT010-NUM001', 'operation_category_id' => 9, 'operation' => 'DETAILS ARCHIVATEDGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'shareBalance', 'relateble_types' => 'history', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 53, 'ref' => 'BAL07-CAT010-NUM001', 'operation_category_id' => 9, 'operation' => 'DETAILS ARCHIVATEDGIFT', 'direction' => 'IN', 'balance_id' => 7, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'chancesBalance', 'relateble_types' => 'history', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 54, 'ref' => 'BAL04-CAT011-NUM001', 'operation_category_id' => 10, 'operation' => 'TREE REMUNARATEDGIFT', 'direction' => 'OUT', 'balance_id' => 4, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 55, 'ref' => 'BAL06-CAT011-NUM001', 'operation_category_id' => 10, 'operation' => 'SOLDED SHARESGIFT', 'direction' => 'OUT', 'balance_id' => 6, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 56, 'ref' => 'BAL07-CAT011-NUM001', 'operation_category_id' => 10, 'operation' => 'JACKPOT WONGIFT', 'direction' => 'OUT', 'balance_id' => 7, 'parent_operation_id' => null, 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 57, 'ref' => 'BAL05-CAT011-NUM001', 'operation_category_id' => 10, 'operation' => 'SMS CONSUMEDGIFT', 'direction' => 'OUT', 'balance_id' => 5, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'sms content', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 58, 'ref' => 'BAL06-CAT007-NUM001', 'operation_category_id' => 6, 'operation' => 'SHARES SELLGIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 59, 'ref' => 'BAL01-CAT007-NUM002', 'operation_category_id' => 6, 'operation' => 'SHARES SELLGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 60, 'ref' => 'BAL02-CAT007-NUM003', 'operation_category_id' => 6, 'operation' => 'SHARES SELLGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => '20', 'relateble' => TRUE, 'relateble_model' => 'user', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 61, 'ref' => 'BAL01-CAT012-NUM001', 'operation_category_id' => 11, 'operation' => 'TOP-UP WITH CARDGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => '20', 'relateble' => FALSE, 'relateble_model' => null, 'relateble_types' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 62, 'ref' => 'BAL01-CAT012-NUM002', 'operation_category_id' => 11, 'operation' => 'CASH TOP-UP WITH VOUCHERGIFT', 'direction' => 'IN', 'balance_id' => 1, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'coupon', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 63, 'ref' => 'BAL06-CAT006-NUM004', 'operation_category_id' => 5, 'operation' => 'FROM BFS_100 GIFT', 'direction' => 'IN', 'balance_id' => 6, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'bfssBalance', 'relateble_types' => 'default', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 64, 'ref' => 'BAL03-CAT009-NUM002', 'operation_category_id' => 8, 'operation' => 'GIFT VOUCHERGIFT', 'direction' => 'IN', 'balance_id' => 3, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'discountBalance', 'relateble_types' => 'note', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 65, 'ref' => 'BAL02-CAT009-NUM003', 'operation_category_id' => 8, 'operation' => 'GIFT VOUCHERGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'bfssBalance', 'relateble_types' => 'note', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 66, 'ref' => 'BAL02-CAT012-NUM004', 'operation_category_id' => 11, 'operation' => 'BFS_100 TOP-UP WITH VOUCHERGIFT', 'direction' => 'IN', 'balance_id' => 2, 'parent_operation_id' => null, 'relateble' => TRUE, 'relateble_model' => 'order', 'relateble_types' => 'coupon', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }

}
