<?php

namespace Database\Seeders;

use Core\Models\translatetabs;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MissingTranslateTabsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $translations = [
            [
                'name' => 'langar',
                'value' => 'العربية',
                'valueEn' => 'Arabic',
                'valueFr' => 'Arabe',
                'valueTr' => 'Arapça',
                'valueEs' => 'Árabe',
                'valueRu' => 'Арабский',
                'valueDe' => 'Arabisch',
            ],
            [
                'name' => 'langfr',
                'value' => 'الفرنسية',
                'valueEn' => 'French',
                'valueFr' => 'Français',
                'valueTr' => 'Fransızca',
                'valueEs' => 'Francés',
                'valueRu' => 'Французский',
                'valueDe' => 'Französisch',
            ],
            [
                'name' => 'langtr',
                'value' => 'التركية',
                'valueEn' => 'Turkish',
                'valueFr' => 'Turc',
                'valueTr' => 'Türkçe',
                'valueEs' => 'Turco',
                'valueRu' => 'Турецкий',
                'valueDe' => 'Türkisch',
            ],
            [
                'name' => 'langen',
                'value' => 'الإنجليزية',
                'valueEn' => 'English',
                'valueFr' => 'Anglais',
                'valueTr' => 'İngilizce',
                'valueEs' => 'Inglés',
                'valueRu' => 'Английский',
                'valueDe' => 'Englisch',
            ],
            [
                'name' => 'langru',
                'value' => 'الروسية',
                'valueEn' => 'Russian',
                'valueFr' => 'Russe',
                'valueTr' => 'Rusça',
                'valueEs' => 'Ruso',
                'valueRu' => 'Русский',
                'valueDe' => 'Russisch',
            ],
            [
                'name' => 'langes',
                'value' => 'الإسبانية',
                'valueEn' => 'Spanish',
                'valueFr' => 'Espagnol',
                'valueTr' => 'İspanyolca',
                'valueEs' => 'Español',
                'valueRu' => 'Испанский',
                'valueDe' => 'Spanisch',
            ],
            [
                'name' => 'langde',
                'value' => 'الألمانية',
                'valueEn' => 'German',
                'valueFr' => 'Allemand',
                'valueTr' => 'Almanca',
                'valueEs' => 'Alemán',
                'valueRu' => 'Немецкий',
                'valueDe' => 'Deutsch',
            ],
            [
                'name' => 'Users balances Recaps',
                'value' => 'ملخصات أرصدة المستخدمين',
                'valueEn' => 'Users balances Recaps',
                'valueFr' => 'Récapitulatifs des soldes des utilisateurs',
                'valueTr' => 'Kullanıcı bakiye özetleri',
                'valueEs' => 'Resúmenes de saldos de usuarios',
                'valueRu' => 'Сводки балансов пользователей',
                'valueDe' => 'Zusammenfassungen der Benutzerguthaben',
            ],
            [
                'name' => 'Business Sectors',
                'value' => 'القطاعات التجارية',
                'valueEn' => 'Business Sectors',
                'valueFr' => 'Secteurs d\'activité',
                'valueTr' => 'İş Sektörleri',
                'valueEs' => 'Sectores empresariales',
                'valueRu' => 'Бизнес-секторы',
                'valueDe' => 'Geschäftsbereiche',
            ],
            [
                'name' => 'Explore our diverse range of business opportunities',
                'value' => 'استكشف مجموعتنا المتنوعة من فرص الأعمال',
                'valueEn' => 'Explore our diverse range of business opportunities',
                'valueFr' => 'Explorez notre gamme diversifiée d\'opportunités commerciales',
                'valueTr' => 'Çeşitli iş fırsatlarımızı keşfedin',
                'valueEs' => 'Explore nuestra diversa gama de oportunidades de negocio',
                'valueRu' => 'Изучите наш разнообразный спектр бизнес-возможностей',
                'valueDe' => 'Entdecken Sie unser vielfältiges Angebot an Geschäftsmöglichkeiten',
            ],
            [
                'name' => 'Database to File Completed',
                'value' => 'اكتمل التصدير من قاعدة البيانات إلى الملف',
                'valueEn' => 'Database to File Completed',
                'valueFr' => 'Exportation de la base de données vers le fichier terminée',
                'valueTr' => 'Veritabanından dosyaya aktarım tamamlandı',
                'valueEs' => 'Exportación de base de datos a archivo completada',
                'valueRu' => 'Экспорт базы данных в файл завершен',
                'valueDe' => 'Datenbank zu Datei Export abgeschlossen',
            ],
            [
                'name' => 'Translation Merge',
                'value' => 'دمج الترجمات',
                'valueEn' => 'Translation Merge',
                'valueFr' => 'Fusion des traductions',
                'valueTr' => 'Çeviri birleştirme',
                'valueEs' => 'Fusión de traducciones',
                'valueRu' => 'Объединение переводов',
                'valueDe' => 'Übersetzungszusammenführung',
            ],
            [
                'name' => 'notifications.order_completed.action',
                'value' => 'عرض الطلب',
                'valueEn' => 'View Order',
                'valueFr' => 'Voir la commande',
                'valueTr' => 'Siparişi görüntüle',
                'valueEs' => 'Ver pedido',
                'valueRu' => 'Просмотреть заказ',
                'valueDe' => 'Bestellung anzeigen',
            ],
            [
                'name' => 'Mark them all as read',
                'value' => 'وضع علامة على الكل كمقروء',
                'valueEn' => 'Mark them all as read',
                'valueFr' => 'Tout marquer comme lu',
                'valueTr' => 'Tümünü okundu olarak işaretle',
                'valueEs' => 'Marcar todos como leídos',
                'valueRu' => 'Отметить все как прочитанные',
                'valueDe' => 'Alle als gelesen markieren',
            ],
            [
                'name' => 'Notifications list Completed',
                'value' => 'قائمة الإشعارات مكتملة',
                'valueEn' => 'Notifications list Completed',
                'valueFr' => 'Liste des notifications terminée',
                'valueTr' => 'Bildirim listesi tamamlandı',
                'valueEs' => 'Lista de notificaciones completada',
                'valueRu' => 'Список уведомлений завершен',
                'valueDe' => 'Benachrichtigungsliste abgeschlossen',
            ],
            [
                'name' => 'notifications.settings.order_completed',
                'value' => 'إشعارات إكمال الطلب',
                'valueEn' => 'Order completion notifications',
                'valueFr' => 'Notifications de commande terminée',
                'valueTr' => 'Sipariş tamamlama bildirimleri',
                'valueEs' => 'Notificaciones de pedido completado',
                'valueRu' => 'Уведомления о завершении заказа',
                'valueDe' => 'Benachrichtigungen über Bestellabschluss',
            ],
            [
                'name' => 'User Menu',
                'value' => 'قائمة المستخدم',
                'valueEn' => 'User Menu',
                'valueFr' => 'Menu utilisateur',
                'valueTr' => 'Kullanıcı Menüsü',
                'valueEs' => 'Menú de usuario',
                'valueRu' => 'Меню пользователя',
                'valueDe' => 'Benutzermenü',
            ],
            [
                'name' => 'Admin Menu',
                'value' => 'قائمة المسؤول',
                'valueEn' => 'Admin Menu',
                'valueFr' => 'Menu administrateur',
                'valueTr' => 'Yönetici Menüsü',
                'valueEs' => 'Menú de administrador',
                'valueRu' => 'Меню администратора',
                'valueDe' => 'Admin-Menü',
            ],
            [
                'name' => 'Balance injector',
                'value' => 'محقن الرصيد',
                'valueEn' => 'Balance injector',
                'valueFr' => 'Injecteur de solde',
                'valueTr' => 'Bakiye enjektörü',
                'valueEs' => 'Inyector de saldo',
                'valueRu' => 'Инжектор баланса',
                'valueDe' => 'Guthaben-Injektor',
            ],
            [
                'name' => 'Users Statistics',
                'value' => 'إحصائيات المستخدمين',
                'valueEn' => 'Users Statistics',
                'valueFr' => 'Statistiques des utilisateurs',
                'valueTr' => 'Kullanıcı İstatistikleri',
                'valueEs' => 'Estadísticas de usuarios',
                'valueRu' => 'Статистика пользователей',
                'valueDe' => 'Benutzerstatistiken',
            ],
            [
                'name' => 'H.A. amount Settings',
                'value' => 'إعدادات مبلغ H.A.',
                'valueEn' => 'H.A. amount Settings',
                'valueFr' => 'Paramètres du montant H.A.',
                'valueTr' => 'H.A. tutar ayarları',
                'valueEs' => 'Configuración de cantidad H.A.',
                'valueRu' => 'Настройки суммы H.A.',
                'valueDe' => 'H.A. Betrag Einstellungen',
            ],
            [
                'name' => 'Good Morning',
                'value' => 'صباح الخير',
                'valueEn' => 'Good Morning',
                'valueFr' => 'Bonjour',
                'valueTr' => 'Günaydın',
                'valueEs' => 'Buenos días',
                'valueRu' => 'Доброе утро',
                'valueDe' => 'Guten Morgen',
            ],
            [
                'name' => 'Everything\'s set',
                'value' => 'كل شيء جاهز',
                'valueEn' => 'Everything\'s set',
                'valueFr' => 'Tout est prêt',
                'valueTr' => 'Her şey hazır',
                'valueEs' => 'Todo está listo',
                'valueRu' => 'Все готово',
                'valueDe' => 'Alles ist bereit',
            ],
            [
                'name' => 'let\'s get started',
                'value' => 'لنبدأ',
                'valueEn' => 'let\'s get started',
                'valueFr' => 'commençons',
                'valueTr' => 'başlayalım',
                'valueEs' => 'empecemos',
                'valueRu' => 'давайте начнем',
                'valueDe' => 'Lass uns anfangen',
            ],
            [
                'name' => 'Complementary information',
                'value' => 'معلومات تكميلية',
                'valueEn' => 'Complementary information',
                'valueFr' => 'Informations complémentaires',
                'valueTr' => 'Tamamlayıcı bilgiler',
                'valueEs' => 'Información complementaria',
                'valueRu' => 'Дополнительная информация',
                'valueDe' => 'Ergänzende Informationen',
            ],
            [
                'name' => 'cont_inscri_email',
                'value' => 'بريد تأكيد التسجيل',
                'valueEn' => 'Registration confirmation email',
                'valueFr' => 'E-mail de confirmation d\'inscription',
                'valueTr' => 'Kayıt onay e-postası',
                'valueEs' => 'Correo de confirmación de registro',
                'valueRu' => 'Письмо подтверждения регистрации',
                'valueDe' => 'Registrierungsbestätigungs-E-Mail',
            ],
            [
                'name' => 'invit_achat_email',
                'value' => 'بريد دعوة الشراء',
                'valueEn' => 'Purchase invitation email',
                'valueFr' => 'E-mail d\'invitation d\'achat',
                'valueTr' => 'Satın alma davet e-postası',
                'valueEs' => 'Correo de invitación de compra',
                'valueRu' => 'Письмо-приглашение к покупке',
                'valueDe' => 'Kaufeinladungs-E-Mail',
            ],
            [
                'name' => 'cart_validate_email',
                'value' => 'بريد التحقق من السلة',
                'valueEn' => 'Cart validation email',
                'valueFr' => 'E-mail de validation du panier',
                'valueTr' => 'Sepet doğrulama e-postası',
                'valueEs' => 'Correo de validación de carrito',
                'valueRu' => 'Письмо подтверждения корзины',
                'valueDe' => 'Warenkorb-Validierungs-E-Mail',
            ],
            [
                'name' => 'discount_plateforme_p',
                'value' => 'خصم المنصة %',
                'valueEn' => 'Platform discount %',
                'valueFr' => 'Réduction plateforme %',
                'valueTr' => 'Platform indirimi %',
                'valueEs' => 'Descuento de plataforma %',
                'valueRu' => 'Скидка платформы %',
                'valueDe' => 'Plattform-Rabatt %',
            ],
            [
                'name' => 'discount_email_p',
                'value' => 'خصم البريد الإلكتروني %',
                'valueEn' => 'Email discount %',
                'valueFr' => 'Réduction e-mail %',
                'valueTr' => 'E-posta indirimi %',
                'valueEs' => 'Descuento de correo %',
                'valueRu' => 'Скидка на email %',
                'valueDe' => 'E-Mail-Rabatt %',
            ],
            [
                'name' => 'discount_sms_p',
                'value' => 'خصم الرسائل النصية %',
                'valueEn' => 'SMS discount %',
                'valueFr' => 'Réduction SMS %',
                'valueTr' => 'SMS indirimi %',
                'valueEs' => 'Descuento SMS %',
                'valueRu' => 'Скидка на SMS %',
                'valueDe' => 'SMS-Rabatt %',
            ],
            [
                'name' => 'validate_phone_email',
                'value' => 'بريد التحقق من الهاتف',
                'valueEn' => 'Phone validation email',
                'valueFr' => 'E-mail de validation du téléphone',
                'valueTr' => 'Telefon doğrulama e-postası',
                'valueEs' => 'Correo de validación de teléfono',
                'valueRu' => 'Письмо подтверждения телефона',
                'valueDe' => 'Telefon-Validierungs-E-Mail',
            ],
            [
                'name' => 'cashBack80_sms',
                'value' => 'رسالة استرداد نقدي 80%',
                'valueEn' => 'CashBack 80% SMS',
                'valueFr' => 'SMS cashback 80%',
                'valueTr' => 'CashBack %80 SMS',
                'valueEs' => 'SMS reembolso 80%',
                'valueRu' => 'SMS кэшбэк 80%',
                'valueDe' => 'CashBack 80% SMS',
            ],
            [
                'name' => 'campagnes_sms',
                'value' => 'رسائل الحملات',
                'valueEn' => 'Campaigns SMS',
                'valueFr' => 'SMS campagnes',
                'valueTr' => 'Kampanya SMS',
                'valueEs' => 'SMS de campañas',
                'valueRu' => 'SMS кампании',
                'valueDe' => 'Kampagnen-SMS',
            ],
            [
                'name' => 'rappel_formation_sms',
                'value' => 'رسالة تذكير التدريب',
                'valueEn' => 'Training reminder SMS',
                'valueFr' => 'SMS rappel de formation',
                'valueTr' => 'Eğitim hatırlatma SMS',
                'valueEs' => 'SMS recordatorio de formación',
                'valueRu' => 'SMS напоминание о обучении',
                'valueDe' => 'Schulungserinnerungs-SMS',
            ],
            [
                'name' => 'discount_sms',
                'value' => 'رسالة الخصم',
                'valueEn' => 'Discount SMS',
                'valueFr' => 'SMS réduction',
                'valueTr' => 'İndirim SMS',
                'valueEs' => 'SMS de descuento',
                'valueRu' => 'SMS скидка',
                'valueDe' => 'Rabatt-SMS',
            ],
            [
                'name' => 'delivery_sms',
                'value' => 'رسالة التوصيل',
                'valueEn' => 'Delivery SMS',
                'valueFr' => 'SMS livraison',
                'valueTr' => 'Teslimat SMS',
                'valueEs' => 'SMS de entrega',
                'valueRu' => 'SMS доставка',
                'valueDe' => 'Liefer-SMS',
            ],
            [
                'name' => 'tree_dead_sms',
                'value' => 'رسالة وفاة الشجرة',
                'valueEn' => 'Tree death SMS',
                'valueFr' => 'SMS arbre mort',
                'valueTr' => 'Ağaç ölümü SMS',
                'valueEs' => 'SMS árbol muerto',
                'valueRu' => 'SMS смерть дерева',
                'valueDe' => 'Baum-Tod-SMS',
            ],
            [
                'name' => 'cont_inscri_sms',
                'value' => 'رسالة تأكيد التسجيل',
                'valueEn' => 'Registration confirmation SMS',
                'valueFr' => 'SMS confirmation d\'inscription',
                'valueTr' => 'Kayıt onay SMS',
                'valueEs' => 'SMS de confirmación de registro',
                'valueRu' => 'SMS подтверждение регистрации',
                'valueDe' => 'Registrierungsbestätigungs-SMS',
            ],
            [
                'name' => 'change_pwd_sms',
                'value' => 'رسالة تغيير كلمة المرور',
                'valueEn' => 'Change password SMS',
                'valueFr' => 'SMS changement de mot de passe',
                'valueTr' => 'Şifre değiştirme SMS',
                'valueEs' => 'SMS cambio de contraseña',
                'valueRu' => 'SMS изменение пароля',
                'valueDe' => 'Passwort ändern SMS',
            ],
            [
                'name' => 'iden_valide_sms',
                'value' => 'رسالة التحقق من الهوية',
                'valueEn' => 'Identity validation SMS',
                'valueFr' => 'SMS validation d\'identité',
                'valueTr' => 'Kimlik doğrulama SMS',
                'valueEs' => 'SMS validación de identidad',
                'valueRu' => 'SMS проверка личности',
                'valueDe' => 'Identitätsvalidierungs-SMS',
            ],
            [
                'name' => 'new_cnx_sms',
                'value' => 'رسالة اتصال جديد',
                'valueEn' => 'New connection SMS',
                'valueFr' => 'SMS nouvelle connexion',
                'valueTr' => 'Yeni bağlantı SMS',
                'valueEs' => 'SMS nueva conexión',
                'valueRu' => 'SMS новое подключение',
                'valueDe' => 'Neue Verbindung SMS',
            ],
        ];

        foreach ($translations as $translation) {
            translatetabs::updateOrCreate(
                ['name' => $translation['name']],
                $translation
            );
        }

        $this->command->info('Missing translation keys have been successfully seeded!');
    }
}

